---
# Atualização de pacotes do SO

- name: Atualizacao do Sistema Operacional
  yum:
    name: "*"
    state: latest
    update_cache: "yes"

- name: Instalação de pacotes
  yum:
    name: "{{ packages }}"
    state: latest 
  vars:
    packages:
      - net-tools
      - vim
      - nmap

# Configuração de TimeZone

- name: Configurando Timezone
  file:
    src: /usr/share/zoneinfo/America/Sao_Paulo
    dest: /etc/localtime
    state: link
    force: "yes"
...
